"""Estado inicial completo con columnas nuevas y defaults

Revision ID: 4514a3c01f14
Revises: 
Create Date: 2026-03-09 19:15:28.389115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4514a3c01f14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_inventario')
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))
        batch_op.alter_column('nombre_parte',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('costo',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.alter_column('costo',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('nombre_parte',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('precio')

    op.create_table('_alembic_tmp_inventario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_parte', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('numero_parte', sa.VARCHAR(length=50), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('costo', sa.FLOAT(), nullable=False),
    sa.Column('proveedor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
