"""Agregar columnas numero_parte, proveedor, costo, precio_publico a Inventario

Revision ID: 93c2d4bd0876
Revises: 177d6472dd9a
Create Date: 2026-03-09 18:49:46.718866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c2d4bd0876'
down_revision = '177d6472dd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.drop_column('precio')
        batch_op.drop_column('proveedor')

    # ### end Alembic commands ###
